# Generated by Django 3.0.11 on 2021-01-08 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dj_proposals_candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('sent', 'sent')], default='draft', max_length=100, no_check_for_status=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_for', to='dj_proposals_candidates.Candidate')),
                ('proposals', models.ManyToManyField(related_name='recommended_in', to='dj_proposals_candidates.Proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
